from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page(viewport={"width": 1440, "height": 1000})
    errors = []
    page.on("requestfailed", lambda req: errors.append(f"failed {req.url}: {req.failure}"))
    page.on("console", lambda msg: errors.append(f"console {msg.type}: {msg.text}") if msg.type == "error" else None)
    page.on("pageerror", lambda err: errors.append(f"pageerror: {err}"))
    page.goto("http://localhost:5173")
    page.wait_for_load_state("networkidle")
    print("title:", page.title())
    print("body length:", len(page.content()))
    print("buttons:", page.locator("button").count())
    print("paper:", page.locator(".cv-paper").count())
    print("body text:", page.locator("body").inner_text().encode("ascii", "replace").decode())
    print("errors:", errors)
    page.locator("[data-template='slate']").click()
    print("slate selected:", page.locator("[data-template='slate'].selected").count())
    page.locator("#font").fill("12")
    print("font setting:", page.locator("#font-out").inner_text())
    page.locator("#json").fill("{bad json")
    print("json error:", page.locator("#validation").inner_text().startswith("JSON needs attention"))
    page.screenshot(path="C:/Users/mfsen/Documents/Codex/2026-07-21/files-mentioned-by-the-user-build/work/app-check.png", full_page=True)
    browser.close()
